// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6lhZaI6O4VIIzUZvpXBcawVe2x5ftKHY',
    appId: '1:341973348488:web:11155359199f055c922f3d',
    messagingSenderId: '341973348488',
    projectId: 'chat-app-64ab1',
    authDomain: 'chat-app-64ab1.firebaseapp.com',
    storageBucket: 'chat-app-64ab1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdygDpsfk1glW5fBo9DLz75Sp6SxoprX8',
    appId: '1:341973348488:android:c4a9a99161d60930922f3d',
    messagingSenderId: '341973348488',
    projectId: 'chat-app-64ab1',
    storageBucket: 'chat-app-64ab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpJYOXYjEDfkzSTgGndke41T88LuF5og',
    appId: '1:341973348488:ios:fc2fb558b5f2c27f922f3d',
    messagingSenderId: '341973348488',
    projectId: 'chat-app-64ab1',
    storageBucket: 'chat-app-64ab1.appspot.com',
    iosClientId: '341973348488-p8v0r40tbi39sbmsc65c2p8ri319sblv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpJYOXYjEDfkzSTgGndke41T88LuF5og',
    appId: '1:341973348488:ios:fc2fb558b5f2c27f922f3d',
    messagingSenderId: '341973348488',
    projectId: 'chat-app-64ab1',
    storageBucket: 'chat-app-64ab1.appspot.com',
    iosClientId: '341973348488-p8v0r40tbi39sbmsc65c2p8ri319sblv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
